### ISSUE TITLE
The git repository is too huge for installation

### ISSUE THREAD

**Issue by asmaier** [hplgit/doconce#121]
It is recommended to clone the repository for installation. But the size of the git repo of doconce is 450 MB. Downloading 450 MB just for installing doconce seems excessive too me. Is all this data really necessary or could the size of the repo be reduced?

**Comment by KGHustad** [comment]
The repository has grown quite large. This is due to the inclusion of all the documentation in various formats. A shallow clone may cut the size in half, but it's still a lot. Installing from [conda](https://anaconda.org/conda-forge/doconce) or [pip](https://pypi.python.org/pypi/Doconce/1.4.3) will require less space.

There isn't much we can do about the size of the current repo, but the next major version of DocOnce will most likely be developed in a new repo with the documentation in a separate repo.
