### ISSUE TITLE
underline and double underline

### ISSUE THREAD

**Issue by zaxebo1** [hplgit/doconce#13]
I want to generate "underline" and "doubleunderline" in final generated PDF, i am not able to see any way in which doconce allows me to do so. Underline is also possible in HTML
Can you kindly enhance it

**Comment by hplgit** [comment]
Underline is seldom supported in markup languages since it is no longer much used in typography (italic is preferred). You can, however, extend the syntax by a writing mako function that returns underline in case of latex and emphasize for all other formats:

```
<%
def underline(text):
    if FORMAT in ('latex', 'pdflatex'):
        return '\\underline{%s}' % text
    else:
        # Use emphasize font
        return '*%s*' % text
%>
```

# In the doconce text:
Here is a sentence with an old-fashioned ${underline('underlined')} word.
