### ISSUE TITLE
Installation fails under Python 3 on Mac

### ISSUE THREAD

**Issue by ketch** [hplgit/doconce#149]
I'm trying to install doconce on a Mac (running OS X 10.12.5) under Python 3.  Installation under Python 2 succeds, but with Python 3, installation of `preprocessor` fails.  I've given more details at https://github.com/hplgit/preprocess/issues/9.  I'm cross-posting here because it looks like perhaps nobody is monitoring issues raised in the preprocessor repo.

**Comment by KGHustad** [comment]
I have considered removing preprocess from the dependencies in `setup.py`, since it's pip will try to install preprocess from PyPi, and there's no good workaround for that. It would at least make the installation process somewhat clearer, even though you would still have to manually install preprocess from GitHub.

**Comment by KGHustad** [comment]
161fb4bbe002e29940f41cb942a51bd96fe1ad78 removes preprocess as a dependency in `setup.py`. preprocess should be installed manually before DocOnce. 

The documentation has been updated to reflect this.
