### ISSUE TITLE
How to convert from .ipynb notebook to .do.txt format?

### ISSUE THREAD

**Issue by ketch** [hplgit/doconce#29]
Is there a tool that automatically takes an IPython notebook and converts it to Doconce format?  I can see two reasons why this would be very useful:
1. I have lots of IPython notebooks; getting them into .do format would allow me to easily publish them in other ways.
2. In my workflow it would be nice to write the document in .do format, convert to .ipynb, run the code and debug it in the notebook, and then convert back to .do.

**Comment by hplgit** [comment]
I have thought about this for a long time but never had the push to find a solution. It was not very difficult, in principle, since the notebook software has a reader. However, doconce generates special references etc. that must be converted back the right way, so there is need for treating a series of special syntax beyond standard markdown.

This new feature takes notebook.ipynb to doconce:

```
doconce ipynb2doconce notebook.ipynb
```
Try (e.g.) `doc/src/ipynb/example.do.txt` to `.ipynb` and then back (take a copy first!). It works okay for me (one loses mako code, but the other elements are in place). There is certainly need for more special cases than what I have thought of. Please report problems.

As a consequence of ipynb2doconce, the ipynb format made by `doconce format ipynb` is now equipped with more comments regarding info from doconce (e.g. index words, labels, figure/movie constructions) such that it becomes easier to translate the notebook back to doconce format.

**Comment by ClaudioVZ** [comment]
Error to convert, example:
<pre>```pascal
function raiz(x_l, x_u)
    x_r = (x_l + x_u)/2
    return x_r
end function
```</pre>

**Comment by hplgit** [comment]
Pascal is not supported as language. You must start with a DocOnce document and generate the notebook from that document. The example you provided is in Markdown.
