### ISSUE TITLE
Figure Caption cannot have _

### ISSUE THREAD

**Issue by nagordon** [hplgit/doconce#31]
Just wanted to make a general comment that confused me and caused a lot of tex errors, The Figure captions apparently cannot have _

This might be handy to include in the documentation. Thanks again

**Comment by hplgit** [comment]
It is a 5 sec fix to prefix underscore with a backslash in figure caption. However, I'm uncertain whether such an automatic fix is confusing: underscore will cause the same problem also in running text - that is a problem of latex, and it is highly nontrivial to autoinsert backslashes in running text.

The idea so far has been to avoid underscores in plain text and only use them in verbatim code: `this_file_name` or `this_function_name`. I suggest to recommend that words with underscores are typeset with verbatim since that will work across all formats. One can also provide format-specific fixes a la

```
% if FORMAT in ('latex', 'pdflatex')
FIGURE: [myfig] Caption with\_underscore.
% else:
FIGURE [myfig] Caption with underscore.
% endif
```
